version: "3.9"

services:
  server1:
    image: wygd/api-servidor1:latest
    hostname: servidor1
    expose:
      - "5000:5000"
    networks:
      - red-servidores
  server2:
    image: wygd/api-servidor2:latest
    hostname: servidor2
    expose:
      - "5001:6000"
    networks:
      - red-servidores
networks:
  red-servidores:
    driver: bridge