// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: calculadora.proto

package calculadora

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op1      int32 `protobuf:"varint,1,opt,name=op1,proto3" json:"op1,omitempty"`
	Op2      int32 `protobuf:"varint,2,opt,name=op2,proto3" json:"op2,omitempty"`
	Operador int32 `protobuf:"varint,3,opt,name=operador,proto3" json:"operador,omitempty"`
}

func (x *Operacion) Reset() {
	*x = Operacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculadora_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operacion) ProtoMessage() {}

func (x *Operacion) ProtoReflect() protoreflect.Message {
	mi := &file_calculadora_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operacion.ProtoReflect.Descriptor instead.
func (*Operacion) Descriptor() ([]byte, []int) {
	return file_calculadora_proto_rawDescGZIP(), []int{0}
}

func (x *Operacion) GetOp1() int32 {
	if x != nil {
		return x.Op1
	}
	return 0
}

func (x *Operacion) GetOp2() int32 {
	if x != nil {
		return x.Op2
	}
	return 0
}

func (x *Operacion) GetOperador() int32 {
	if x != nil {
		return x.Operador
	}
	return 0
}

type Resultado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resultado int32  `protobuf:"varint,1,opt,name=resultado,proto3" json:"resultado,omitempty"`
	Mensaje   string `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
}

func (x *Resultado) Reset() {
	*x = Resultado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculadora_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resultado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resultado) ProtoMessage() {}

func (x *Resultado) ProtoReflect() protoreflect.Message {
	mi := &file_calculadora_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resultado.ProtoReflect.Descriptor instead.
func (*Resultado) Descriptor() ([]byte, []int) {
	return file_calculadora_proto_rawDescGZIP(), []int{1}
}

func (x *Resultado) GetResultado() int32 {
	if x != nil {
		return x.Resultado
	}
	return 0
}

func (x *Resultado) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_calculadora_proto protoreflect.FileDescriptor

var file_calculadora_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x72, 0x61,
	0x22, 0x4b, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6f, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70, 0x31, 0x12,
	0x10, 0x0a, 0x03, 0x6f, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6f, 0x70,
	0x32, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x43, 0x0a,
	0x09, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x73,
	0x61, 0x6a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x32, 0x4e, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x72,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x72, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x72, 0x61,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x64, 0x6f, 0x72, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x61,
	0x64, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculadora_proto_rawDescOnce sync.Once
	file_calculadora_proto_rawDescData = file_calculadora_proto_rawDesc
)

func file_calculadora_proto_rawDescGZIP() []byte {
	file_calculadora_proto_rawDescOnce.Do(func() {
		file_calculadora_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculadora_proto_rawDescData)
	})
	return file_calculadora_proto_rawDescData
}

var file_calculadora_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculadora_proto_goTypes = []interface{}{
	(*Operacion)(nil), // 0: calculadora.Operacion
	(*Resultado)(nil), // 1: calculadora.Resultado
}
var file_calculadora_proto_depIdxs = []int32{
	0, // 0: calculadora.CalculadoraService.Operar:input_type -> calculadora.Operacion
	1, // 1: calculadora.CalculadoraService.Operar:output_type -> calculadora.Resultado
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculadora_proto_init() }
func file_calculadora_proto_init() {
	if File_calculadora_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calculadora_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculadora_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resultado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculadora_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculadora_proto_goTypes,
		DependencyIndexes: file_calculadora_proto_depIdxs,
		MessageInfos:      file_calculadora_proto_msgTypes,
	}.Build()
	File_calculadora_proto = out.File
	file_calculadora_proto_rawDesc = nil
	file_calculadora_proto_goTypes = nil
	file_calculadora_proto_depIdxs = nil
}
